FROM ubuntu:18.04 as ui-builder
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
RUN apt-get update && \
  apt install -y  build-essential python-dev git jq wget curl nano openssh-server ngrep tmux net-tools screen vim

#RUN curl -sL https://deb.nodesource.com/setup_13.x -o nodesource_setup.sh && \
RUN curl -sL https://deb.nodesource.com/setup_14.x -o nodesource_setup.sh && \
  bash nodesource_setup.sh && \
  apt install -y nodejs && \
  npm config set prefix ~/.local && \
  echo "PATH=~/.local/bin/:\$PATH" >> ~/.bashrc

COPY . /app
RUN npm install
RUN npm run build

FROM nginx
COPY --from=ui-builder /app/dist/ /usr/share/nginx/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
